apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  template:
    metadata:
      name: petclinic
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: myawesomeapps/petclinic:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m" # 1/4 core
            limits:
              memory: "1024Mi"
              cpu: "1000m" # 1 core
  replicas: 1
  selector:
    matchLabels:
      app: petclinic

---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  type: LoadBalancer
  selector:
    app: petclinic
  ports:
  - port: 80
    targetPort: 8080

